version: "3.8"version: "3.8"
services:
  nginx:
    image: nginx:alpine
    networks:
      - duo-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
  flask-app:
    image: duotask/duo-app:v1
    build: .
networks:
  duo-net:
deploy:
  replicas: 3

