version: "3.8"
services:
  nginx:
    image: nginx:alpine
    networks:
      - trio-task-network
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
  flask-app:
    image: triotask/trio:V1
    build: .
networks:
  duo-net:
deploy:
  replicas: 3
